language: python

python:
- "3.5"

install: 
  - pip install -qq flake8
  - pip install --user codecov
  - python setup.py install

script: 
  - python setup.py pytest
  - flake8 --version
  - flake8 iexfinance

after_success:
  - codecov