site_name: IEX Finance Docs
pages:
- Home: index.md
- Installation: install.md
- Usage: usage.md
- Stocks: stocks.md
- Historical Data: historical.md
- Reference Data : ref.md
- IEX Market Data: market.md
- IEX Stats: stats.md
- Caching Queries: caching.md
- Testing: testing.md
- What's New: whatsnew.md
- About: about.md
- Tutorial: tutorial.md
theme: readthedocs