site_name: IEX Finance Docs
pages:
- Home: index.md
- Installation: install.md
- Usage: usage.md
- Share: share.md
- Batch: batch.md
- Utilities : utilities.md
- Testing: testing.md
- Change Log: changes.md
- About: about.md
- Tutorial: tutorial.md
theme: readthedocs